#!/usr/bin/env sh
set -e

usage() {
    echo "usage: git semver <subcommand>"
    echo
    echo "Available subcommands are:"
    echo "  get           Returns the current semantic version, as defined by configurations."
}

version() {
    echo "semver git plugin v0.1.0"
    echo
}

main() {
    git status > /dev/null;

    if [ $? -ne 0 ]
    then
        echo "fatal: Not a git repository (or any of the parent directories): .git" >&2;
        exit 128;
    fi

    if [ "$#" -lt 1 ]; then
        usage; exit 1
    fi

    local subcommand="$1"; shift

    case $subcommand in
        "-h")
            usage; exit 0
            ;;
        "-v"|"--version")
            version; exit 0
            ;;
    esac

    if [ -z "${@##*--verbose*}" ]
    then
        VERBOSE=true;
    fi

    local workingdir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
    local subcmdFile="$workingdir/git-semver-$subcommand.sh"
    if [ ! -e $subcmdFile ]; then
        usage; exit 1
    fi

    source $subcmdFile

    #if [ ! type "main_$subcommand" ]; then
    #    usage; exit 1
    #fi

    if [ $VERBOSE ]
    then   
        echo "Executing subcommand $subcommand from $subcmdFile.";
    fi

    main_$subcommand "$@"
}

main "$@"