#!/usr/bin/env sh

usage() {
    echo "usage: git semver <subcommand>"
    echo
    echo "Available subcommands are:"
    echo "hello <name>  Print out Hello World or Hello <name> (if provided)"
}

version() {
    echo "semver git plugin v0.1.0"
    echo
}

main() {
    if [ "$#" -lt 1 ]; then
        usage; exit 1
    fi

    local subcommand="$1"; shift

    case $subcommand in
        "-h"|"--help")
            usage; exit 0
            ;;
        "-v"|"--version")
            version; exit 0
            ;;
    esac

    local workingdir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
    local subcmdFile="$workingdir/git-semver-$subcommand.sh"
    if [ ! -e $subcmdFile ]; then
        usage; exit 1
    fi

    source $subcmdFile

    if [ ! type "main_$subcommand" ]; then
        usage; exit 1
    fi

    main_$subcommand "$@"
}

main "$@"